export const DEFAULT_EVENTS = [
  'leaf_set',
  'listen',
  'unlisten',
  'call',
  'append_child',
  'remove_child_at',
  'input',
  'output',
  'ref_input',
  'ref_output',
  'err',
  'take_err',
  'catch_err',
  // 'set_input',
  // 'set_output',
  // 'remove_input',
  // 'remove_output',
  'add_unit',
  'remove_unit',
  'move_unit',
  'add_merge',
  'remove_merge',
  'expose_pin',
  'cover_pin',
  'plug_pin',
  'unplug_pin',
  'leaf_set',
  'leaf_add_unit',
  'leaf_remove_unit',
  'leaf_expose_pin_set',
  'leaf_cover_pin_set',
  'leaf_append_child',
  'leaf_remove_child_at',
]
