export const INHERITANCE = {
  S: ['EE'],
  U: ['EE', 'J'],
  G: ['U', 'C'],
  C: ['U'],
  V: ['EE', 'BO'],
  CH: ['EE'],
  IB: ['I'],
  W: ['EE', 'CH'],
  B: ['IM', 'BO'],
  FD: ['BO'],
  ID: ['J'],
  SE: ['EE', 'A', 'J'],
  WSS: ['EE', 'A', 'J'],
  RES: ['BO', 'J', 'V'],
  RS: ['BO'],
  BSN: ['AN', 'EE'],
}
